<?php
/**
 * QR Menu Themes - Profesyonel, gelişmiş tema sistemi
 * Her tema: layout, tipografi, kart stili, animasyon - tam farklı görünüm
 */

$MENU_THEMES = [
    'default' => [
        'name_tr' => 'Klasik',
        'name_en' => 'Classic',
        'desc_tr' => 'Temiz, profesyonel',
        'desc_en' => 'Clean, professional',
        'layout' => 'classic',
        'card_style' => 'rounded',
        'item_layout' => 'horizontal',
        'cat_style' => 'pills',
        'welcome_style' => 'bubble',
        'font_heading' => 'Outfit',
        'font_body' => 'Inter',
        'font_scale' => 'medium',
        'spacing' => 'normal',
        'animation' => 'subtle',
        'bg' => 'linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%)',
        'primary' => '#0055FF',
        'accent' => '#3b82f6',
        'card_bg' => '#ffffff',
        'card_border' => 'rgba(15, 23, 42, 0.06)',
        'card_shadow' => '0 2px 12px rgba(15, 23, 42, 0.06)',
        'card_radius' => '20px',
        'welcome_bg' => '#ffffff',
    ],
    'elegant' => [
        'name_tr' => 'Şık',
        'name_en' => 'Elegant',
        'desc_tr' => 'Zarif, sofistike, serif',
        'desc_en' => 'Sophisticated, serif typography',
        'layout' => 'classic',
        'card_style' => 'bordered',
        'item_layout' => 'horizontal',
        'cat_style' => 'pills',
        'welcome_style' => 'card',
        'font_heading' => 'Playfair Display',
        'font_body' => 'Lora',
        'font_scale' => 'large',
        'spacing' => 'relaxed',
        'animation' => 'subtle',
        'bg' => 'linear-gradient(165deg, #fdfbf7 0%, #f5f0e8 50%, #faf6f1 100%)',
        'primary' => '#8b6914',
        'accent' => '#a67c52',
        'card_bg' => '#ffffff',
        'card_border' => 'rgba(139, 105, 20, 0.2)',
        'card_shadow' => 'none',
        'card_radius' => '12px',
        'welcome_bg' => 'linear-gradient(135deg, #fdfbf7 0%, #fff9f0 100%)',
    ],
    'modern' => [
        'name_tr' => 'Modern',
        'name_en' => 'Modern',
        'desc_tr' => 'Koyu, keskin, tech',
        'desc_en' => 'Dark, sharp, tech',
        'layout' => 'hero',
        'card_style' => 'glass',
        'item_layout' => 'horizontal',
        'cat_style' => 'segmented',
        'welcome_style' => 'minimal',
        'font_heading' => 'Space Grotesk',
        'font_body' => 'DM Sans',
        'font_scale' => 'medium',
        'spacing' => 'normal',
        'animation' => 'pronounced',
        'bg' => 'linear-gradient(180deg, #0f172a 0%, #1e293b 50%, #0f172a 100%)',
        'primary' => '#22d3ee',
        'accent' => '#38bdf8',
        'card_bg' => 'rgba(30, 41, 59, 0.85)',
        'card_border' => 'rgba(34, 211, 238, 0.15)',
        'card_shadow' => '0 4px 24px rgba(0, 0, 0, 0.3)',
        'card_radius' => '16px',
        'welcome_bg' => 'transparent',
        'dark' => true,
    ],
    'minimal' => [
        'name_tr' => 'Minimal',
        'name_en' => 'Minimal',
        'desc_tr' => 'Sade, bol beyaz alan',
        'desc_en' => 'Simple, lots of whitespace',
        'layout' => 'compact',
        'card_style' => 'flat',
        'item_layout' => 'compact',
        'cat_style' => 'tabs',
        'welcome_style' => 'minimal',
        'font_heading' => 'Inter',
        'font_body' => 'Inter',
        'font_scale' => 'small',
        'spacing' => 'relaxed',
        'animation' => 'none',
        'bg' => '#ffffff',
        'primary' => '#18181b',
        'accent' => '#3f3f46',
        'card_bg' => '#ffffff',
        'card_border' => '#e4e4e7',
        'card_shadow' => 'none',
        'card_radius' => '8px',
        'welcome_bg' => '#fafafa',
    ],
    'cozy' => [
        'name_tr' => 'Sıcak',
        'name_en' => 'Cozy',
        'desc_tr' => 'Samimi, yuvarlak köşeler',
        'desc_en' => 'Warm, soft corners',
        'layout' => 'classic',
        'card_style' => 'rounded',
        'item_layout' => 'horizontal',
        'cat_style' => 'pills',
        'welcome_style' => 'bubble',
        'font_heading' => 'Nunito',
        'font_body' => 'Nunito Sans',
        'font_scale' => 'large',
        'spacing' => 'relaxed',
        'animation' => 'subtle',
        'bg' => 'linear-gradient(180deg, #fef7ed 0%, #fffbeb 50%, #fef3c7 100%)',
        'primary' => '#d97706',
        'accent' => '#f59e0b',
        'card_bg' => '#ffffff',
        'card_border' => 'rgba(217, 119, 6, 0.12)',
        'card_shadow' => '0 4px 20px rgba(217, 119, 6, 0.06)',
        'card_radius' => '24px',
        'welcome_bg' => 'linear-gradient(135deg, #fff7ed 0%, #ffedd5 100%)',
    ],
    'luxury' => [
        'name_tr' => 'Lüks',
        'name_en' => 'Luxury',
        'desc_tr' => 'Altın, premium, magazine',
        'desc_en' => 'Gold, premium, magazine',
        'layout' => 'magazine',
        'card_style' => 'elevated',
        'item_layout' => 'vertical',
        'cat_style' => 'tabs',
        'welcome_style' => 'hero',
        'font_heading' => 'Cormorant Garamond',
        'font_body' => 'Cormorant',
        'font_scale' => 'large',
        'spacing' => 'relaxed',
        'animation' => 'subtle',
        'bg' => 'linear-gradient(180deg, #1c1917 0%, #292524 50%, #1c1917 100%)',
        'primary' => '#d4af37',
        'accent' => '#f0d78c',
        'card_bg' => 'rgba(41, 37, 36, 0.95)',
        'card_border' => 'rgba(212, 175, 55, 0.2)',
        'card_shadow' => '0 8px 32px rgba(0, 0, 0, 0.4)',
        'card_radius' => '12px',
        'welcome_bg' => 'linear-gradient(135deg, rgba(212,175,55,0.15) 0%, transparent 100%)',
        'dark' => true,
    ],
    'bistro' => [
        'name_tr' => 'Bistro',
        'name_en' => 'Bistro',
        'desc_tr' => 'Rustik, rahat, editorial',
        'desc_en' => 'Rustic, casual, editorial',
        'layout' => 'magazine',
        'card_style' => 'bordered',
        'item_layout' => 'horizontal',
        'cat_style' => 'buttons',
        'welcome_style' => 'card',
        'font_heading' => 'Merriweather',
        'font_body' => 'Source Sans 3',
        'font_scale' => 'medium',
        'spacing' => 'normal',
        'animation' => 'none',
        'bg' => 'linear-gradient(180deg, #f5f5f4 0%, #e7e5e4 100%)',
        'primary' => '#78716c',
        'accent' => '#a8a29e',
        'card_bg' => '#fafaf9',
        'card_border' => 'rgba(120, 113, 108, 0.25)',
        'card_shadow' => '0 1px 3px rgba(0,0,0,0.05)',
        'card_radius' => '12px',
        'welcome_bg' => '#fefce8',
    ],
    'zarif' => [
        'name_tr' => 'Zarif',
        'name_en' => 'Refined',
        'desc_tr' => 'İnce çizgiler, sade zarafet',
        'desc_en' => 'Subtle lines, understated',
        'layout' => 'classic',
        'card_style' => 'bordered',
        'item_layout' => 'horizontal',
        'cat_style' => 'pills',
        'welcome_style' => 'card',
        'font_heading' => 'Cormorant',
        'font_body' => 'Libre Baskerville',
        'font_scale' => 'medium',
        'spacing' => 'relaxed',
        'animation' => 'subtle',
        'bg' => 'linear-gradient(175deg, #faf9f7 0%, #f3f1ee 50%, #f8f6f3 100%)',
        'primary' => '#6b5b4f',
        'accent' => '#8b7355',
        'card_bg' => '#ffffff',
        'card_border' => 'rgba(107, 91, 79, 0.12)',
        'card_shadow' => '0 1px 3px rgba(107, 91, 79, 0.04)',
        'card_radius' => '16px',
        'welcome_bg' => '#fdfcfb',
    ],
];

function get_menu_theme($theme_id, $primary_color_override = null) {
    global $MENU_THEMES;
    $theme_id = $theme_id ?? 'default';
    if (!isset($MENU_THEMES[$theme_id])) $theme_id = 'default';
    $t = $MENU_THEMES[$theme_id];
    if ($primary_color_override && preg_match('/^#[0-9a-fA-F]{6}$/', $primary_color_override)) {
        $t['primary'] = $primary_color_override;
        $t['accent'] = $primary_color_override;
    }
    return $t;
}

function get_menu_theme_fonts_url($theme_id) {
    $fonts = [
        'default' => 'Outfit:wght@400;600;700;800;900&family=Inter:wght@400;500;600;700&display=swap',
        'elegant' => 'Playfair+Display:wght@400;600;700&family=Lora:ital,wght@0,400;0,600;1,400&display=swap',
        'modern' => 'Space+Grotesk:wght@400;600;700&family=DM+Sans:wght@400;500;600;700&display=swap',
        'minimal' => 'Inter:wght@300;400;500;600;700&display=swap',
        'cozy' => 'Nunito:wght@400;600;700;800&family=Nunito+Sans:wght@400;600;700&display=swap',
        'luxury' => 'Cormorant+Garamond:ital,wght@0,400;0,600;0,700;1,400&family=Cormorant:wght@400;600&display=swap',
        'bistro' => 'Merriweather:wght@400;700&family=Source+Sans+3:wght@400;600;700&display=swap',
        'zarif' => 'Cormorant:wght@400;600&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap',
    ];
    return $fonts[$theme_id ?? 'default'] ?? $fonts['default'];
}
